baseURL: "https://jayachristina.github.io/solution-patterns"
theme: "up-business-theme"
languageCode: "en-us"

title: "Solution Patterns from Red Hat"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Solution Patterns"
  description: "Discover the art of the possible with Red Hat's rich portfolio with real world usecases."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: 
    instagram: 
    facebook: 
    twitter: 

  contact:
    - "jaya@redhat.com"
    - "207.555.0119"

  copyright: "Â© 2024 Red Hat"

menus:
  main:
    - name: "Explore Patterns"
      url: "/patterns"
      weight: 2

    - name: "Architecture Center"
      url: "https://www.redhat.com/architect/portfolio/"
      weight: 3

    - name: "Red Hat Developer"
      url: "https://developers.redhat.com/"
      weight: 4

    - name: "Contribute"
      url: "/contribute"
      weight: 5

    - name: "Feedback"
      url: "https://github.com/redhat-solution-patterns/redhat-solution-patterns.github.io/issues"
      weight: 5

  
  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
